'''
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Libraries 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
'''

import torch
import torch.nn as nn
import torch.nn.functional as F

import os
import sys
current = os.path.dirname(os.path.realpath(__file__))
parent = os.path.dirname(current)
sys.path.append(parent)

from Graph.ndp_graph import Node, Graph


'''
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Utilities
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
'''

# Compute action from environment
def compute_action(env_name, action):
    if env_name == 'CartPole-v1':
        action =  torch.sigmoid(action)
        return int(torch.round(action))
    elif env_name in ['MountainCar-v0', 'Acrobot-v1']:
        # return int(nn.functional.hardtanh(action, 0, 2))
        probs = F.softmax(action, dim=0)  
        return int(probs.argmax())
    elif env_name == 'LunarLander-v3':
        # return int(nn.functional.hardtanh(action, 0, 3))
        probs = F.softmax(action, dim=0)  
        return int(probs.argmax())


'''
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Artificial Neural Network created from a graph generated by an NDP
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
'''

class GraphANN(nn.Module):

    def __init__(self, graph:Graph, n_inputs, n_outputs):
        super().__init__()
        
        self.graph = graph
        self.graph_diameter = self.graph.get_diameter()

        self.input_nodes = [i for i in range(n_inputs)]
        self.output_nodes = [i for i in range(n_inputs, n_inputs + n_outputs)]
        self.n_nodes = max(len(graph.nodes), n_inputs + n_outputs)

        weights = torch.zeros((self.n_nodes, self.n_nodes), dtype=torch.float32)

        for (input_node, output_node), edge_weight in graph.edges.items():
            weights[input_node, output_node] = edge_weight

        self.register_buffer('weights', weights)

    def forward(self, x, steps=None):

        if steps is None:
            steps = max(1, self.graph_diameter)

        batch_size = x.shape[0]

        activations = torch.zeros(
            batch_size,
            self.n_nodes,
            dtype=torch.float32,
            device=x.device
        )

        activations[:, self.input_nodes] = x

        for _ in range(steps-1):
            new_activations = activations @ self.weights
            new_activations = torch.tanh(new_activations)
            new_activations[:, self.input_nodes] = x
            activations = new_activations

        new_activations = activations @ self.weights
        return new_activations[:, self.output_nodes]
                                         
                        











