'''
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Libraries 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
'''

import torch
import torch.nn as nn

import os
import sys
current = os.path.dirname(os.path.realpath(__file__))
parent = os.path.dirname(current)
sys.path.append(parent)

from Graph.ndp_graph import Graphnx


'''
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Artificial Neural Network created from a graph generated by an NDP
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
'''

class PolicyNetwork(nn.Module):

    def __init__(self, graph:Graphnx, n_inputs, n_outputs):
        super().__init__()
        
        self.graph = graph
        self.graph_diameter = self.graph.get_diameter()
        
        self.n_inputs, self.n_outputs = n_inputs, n_outputs
        self.n_nodes = graph.number_of_nodes()
        weights = torch.tensor(graph.get_adjacency_matrix(), dtype=torch.float32)

        if self.n_nodes < n_inputs + n_outputs:
            temp_n_nodes = n_inputs + n_outputs
            temp_weights = torch.zeros((temp_n_nodes, temp_n_nodes), dtype=torch.float32)
            temp_weights[:self.n_nodes, :self.n_nodes] = weights
            self.n_nodes = temp_n_nodes
            weights = temp_weights

        self.register_buffer('weights', weights)

    def forward(self, x, steps=None):

        if steps is None:
            steps = max(1, self.graph_diameter)

        batch_size = x.shape[0]

        activations = torch.zeros(
            batch_size,
            self.n_nodes,
            dtype=torch.float32,
            device=x.device
        )

        activations[:, :self.n_inputs] = x
        for _ in range(steps-1):
            new_activations = activations @ self.weights
            new_activations = torch.tanh(new_activations)
            new_activations[:, :self.n_inputs] = x
            activations = new_activations
        new_activations = activations @ self.weights
        return new_activations[:, -self.n_outputs:]
                                         
                        











