'''
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Libraries 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
'''

import jax
import jax.numpy as jnp

from typing import NamedTuple

import os
import sys
current = os.path.dirname(os.path.realpath(__file__))
parent = os.path.dirname(current)
sys.path.append(parent)

from Graph.graph_jax import GraphJax

'''
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Artificial Neural Network created from a graph generated by an NDP
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
'''

class PolicyNetworkJax:

    def __init__(self, n_inputs:int, n_outputs:int, network_extra_thinking:int):
        
        self.n_inputs = n_inputs
        self.n_outputs = n_outputs
        self.network_extra_thinking = network_extra_thinking

    def forward(self, graph:GraphJax, x:jax.Array, steps:int=None):

        raise ValueError('YOU HAVE NOT COMPUTED THE STEPS! ADD IT TO THE TASK!')
        
        # Set up input values
        x = jnp.asarray(x, jnp.float32)
        x = x[None, :] if x.ndim == 1 else x

        # Set up initial graph
        weights = jnp.where(graph.adjacency, graph.weights, 0.0)
        activations = jnp.zeros((x.shape[0], graph.max_nodes), dtype=jnp.float32)
        activations = activations.at[:, :self.n_inputs].set(x)

        # Step function
        def propagation_step(_, activations):
            new_activations = activations @ weights
            new_activations = jnp.tanh(new_activations)
            new_activations = new_activations.at[:, :self.n_inputs].set(x)
            return new_activations

        # Propagate through n-1 steps
        activations = jax.lax.fori_loop(0, steps-1, propagation_step, activations)

        # Compute output layer (no activation so it can be computed independently for each task outside the function)
        output_activations = activations @ weights

        # Return the output nodes
        n_active = graph.number_of_nodes()
        output_start = n_active - self.n_outputs
        return jax.lax.dynamic_slice_in_dim(output_activations, output_start, self.n_outputs, axis=1)

                        
'''
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Artificial Neural Network created from a graph generated by an NDP that uses Neural Centric Hebbian Learning (NcHL)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
'''

class HebbianPolicyState(NamedTuple):
    weights: jax.Array

class NcHebbianLearningPolicyNetworkJax(PolicyNetworkJax):

    def __init__(self, n_inputs:int, n_outputs:int, network_extra_thinking:int):
        super().__init__(n_inputs, n_outputs, network_extra_thinking)

    def initial_state(self, graph:GraphJax) -> HebbianPolicyState:
        weights = jnp.where(graph.adjacency, graph.weights, 0.0)
        return HebbianPolicyState(weights)

    def get_hebbian_matrix(self, graph:GraphJax) -> tuple:
        hebbian_coeff = graph.nodes_states[:, :5]

        # ETA = (etai + etaj)/2
        ETA = (hebbian_coeff[:, None, 0] + hebbian_coeff[None, :, 0]) / 2.0

        # A = Ai
        A = jnp.broadcast_to(hebbian_coeff[:, None, 1], (graph.max_nodes, graph.max_nodes))

        # B = Bj
        B = jnp.broadcast_to(hebbian_coeff[None, :, 2], (graph.max_nodes, graph.max_nodes))

        # C = Ci*Cj
        C = hebbian_coeff[:, None, 3] * hebbian_coeff[None, :, 3]


        # D = Di*Dj
        D = hebbian_coeff[:, None, 4] * hebbian_coeff[None, :, 4]

        return ETA, A, B, C, D

    def hebbian_update(self, weights:jax.Array, pre:jax.Array, post:jax.Array, hebbian_matrix:tuple, adjacency:jax.Array) -> jax.Array:
        ETA, A, B, C, D = hebbian_matrix

        pre = pre.squeeze(0)
        post = post.squeeze(0)

        pre_i = pre[:, None]
        post_j = post[None, :]

        # delta = (etai+etaj/2) * (Ai*pre + Bj*post + Ci*Cj*pre*post + Di*Dj)
        delta = ETA * (
            A * pre_i
            + B * post_j
            + C * pre_i * post_j
            + D
        )

        delta = jnp.where(adjacency, delta, 0.0)
        return weights + delta

    def forward(self, graph:GraphJax, x:jax.Array, policy_state: HebbianPolicyState, steps:int) -> tuple[jax.Array, HebbianPolicyState]:
        # Set up input values
        x = jnp.asarray(x, jnp.float32)
        x = x[None, :] if x.ndim == 1 else x

        # Set up initial graph
        weights = policy_state.weights
        activations = jnp.zeros((x.shape[0], graph.max_nodes), dtype=jnp.float32)
        activations = activations.at[:, :self.n_inputs].set(x)
        hebbian_matrix = self.get_hebbian_matrix(graph)

        # Step function
        def propagation_step(_, carry):
            activations, weights = carry
            new_activations = activations @ weights
            new_activations = jnp.tanh(new_activations)
            new_activations = new_activations.at[:, :self.n_inputs].set(x)

            new_weights = self.hebbian_update(weights, activations, new_activations, hebbian_matrix, graph.adjacency)

            return new_activations, new_weights

        # Propagate through n-1 steps
        activations, weights = jax.lax.fori_loop(0, steps-1, propagation_step, (activations, weights))

        # Compute output layer (no activation so it can be computed independently for each task outside the function)
        output_activations = activations @ weights
        new_weights = self.hebbian_update(weights, activations, output_activations, hebbian_matrix, graph.adjacency)
        new_policy_state = HebbianPolicyState(new_weights)

        # Return the output nodes
        n_active = graph.number_of_nodes()
        output_start = n_active - self.n_outputs
        outputs = jax.lax.dynamic_slice_in_dim(output_activations, output_start, self.n_outputs, axis=1)

        return outputs, new_policy_state





                                         
                        





if __name__ == '__main__':
    pass

    # N = 10

    # matrix = [[x for _ in range(5)] for x in range(N)] 

    # matrix = torch.tensor(matrix)

    # result = matrix[:, None, :] * matrix[None, :, :]
    # result[:,:,1:3] = matrix[:,None,1:3]

    # print(result[:, :, 0])
    # print(result[0, 1, 0])
    # print(result[:, :, 1])
    # print(result.shape)














