'''
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Libraries 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
'''

import numpy as np
import torch
import torch.nn as nn

import os
import sys
current = os.path.dirname(os.path.realpath(__file__))
parent = os.path.dirname(current)
sys.path.append(parent)

from Graph.graph import Graphnx


'''
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Artificial Neural Network created from a graph generated by an NDP
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
'''

class PolicyNetwork(nn.Module):

    def __init__(self, graph:Graphnx, n_inputs, n_outputs, network_extra_thinking):
        super().__init__()
        
        self.graph = graph
        self.graph_diameter = self.graph.get_largest_subgraph_diameter()
        self.network_extra_thinking = network_extra_thinking
        
        self.n_inputs, self.n_outputs = n_inputs, n_outputs
        self.n_nodes = graph.number_of_nodes()
        weights = torch.tensor(graph.get_adjacency_matrix(), dtype=torch.float32)

        if self.n_nodes < n_inputs + n_outputs:
            temp_n_nodes = n_inputs + n_outputs
            temp_weights = torch.zeros((temp_n_nodes, temp_n_nodes), dtype=torch.float32)
            temp_weights[:self.n_nodes, :self.n_nodes] = weights
            self.n_nodes = temp_n_nodes
            weights = temp_weights

        self.register_buffer('weights', weights)

    def forward(self, x:torch.Tensor, steps:int=None):

        if steps is None:
            steps = max(1, self.graph_diameter + self.network_extra_thinking)

        batch_size = x.shape[0]

        activations = torch.zeros(batch_size, self.n_nodes, dtype=torch.float32, device=x.device)
        activations[:, :self.n_inputs] = x

        for _ in range(steps-1):
            new_activations = activations @ self.weights
            new_activations = torch.tanh(new_activations)
            new_activations[:, :self.n_inputs] = x
            activations = new_activations
        new_activations = activations @ self.weights
        return new_activations[:, -self.n_outputs:]
                                         
                        
'''
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Artificial Neural Network created from a graph generated by an NDP that uses Neural Centric Hebbian Learning (NcHL)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
'''

class NcHebbianLearningPolicyNetwork(PolicyNetwork):

    def __init__(self, graph:Graphnx, n_inputs:int, n_outputs:int, network_extra_thinking:int):
        super().__init__(graph, n_inputs, n_outputs, network_extra_thinking)

        # Check that the all nodes have a state
        if self.n_nodes > len(graph.nodes_states):
            self.nodes_states = np.zeros((self.n_nodes, graph.state_dim))
            self.nodes_states[:len(graph.nodes_states), :] = graph.nodes_states
        else:
            self.nodes_states = graph.nodes_states.copy()

        # Create Hebbian Matrix based on Neuron-centric Hebbian Learning (NcHL)
        self.hebbian_coeff = np.array(self.nodes_states)[:, :5]
        self.hebbian_coeff = torch.tensor(self.hebbian_coeff, dtype=torch.float32)
        self.hebbian_matrix = torch.empty((self.n_nodes, self.n_nodes, 5))

        # ETA = (etai + etaj)/2
        self.hebbian_matrix[:, :, 0] = (self.hebbian_coeff[:, None, 0] + self.hebbian_coeff[None, :, 0]) / 2
        
        # A = Ai
        self.hebbian_matrix[:, :, 1] = self.hebbian_coeff[:, None, 1]

        # B = Bj
        self.hebbian_matrix[:, :, 2] = self.hebbian_coeff[None, :, 1]

        # C = Ci*Cj and D = Di*Dj
        self.hebbian_matrix[:, :, 3:5] = self.hebbian_coeff[:, None, 3:5] * self.hebbian_coeff[None, :, 3:5]


    def hebbian_update(self, weights, pre, post):
        with torch.no_grad():
            ETA, A, B, C, D = self.hebbian_matrix.unbind(dim=2)

            # Check __init__ for context
            # delta = (etai+etaj/2) * (Ai*pre + Bj*post + Ci*Cj*pre*post + Di*Dj)
            delta = ETA * ( 
                A * pre +
                B * post +
                C * (post @ pre.T) + 
                D
            )

        return weights + delta


    def forward(self, x:torch.Tensor, steps:int=None):

        if steps is None:
            steps = max(1, self.graph_diameter + self.network_extra_thinking)

        batch_size = x.shape[0]

        activations = torch.zeros(batch_size, self.n_nodes, dtype=torch.float32, device=x.device)
        activations[:, :self.n_inputs] = x

        weights = self.weights.clone() 

        for _ in range(steps-1):
            new_activations = activations @ weights
            new_activations = torch.tanh(new_activations)
            new_activations[:, :self.n_inputs] = x
            weights = self.hebbian_update(weights, activations, new_activations)
            activations = new_activations
        new_activations = activations @ self.weights
        return new_activations[:, -self.n_outputs:]
                                         
                        





if __name__ == '__main__':

    N = 10

    matrix = [[x for _ in range(5)] for x in range(N)] 

    matrix = torch.tensor(matrix)

    result = matrix[:, None, :] * matrix[None, :, :]
    result[:,:,1:3] = matrix[:,None,1:3]

    print(result[:, :, 0])
    print(result[0, 1, 0])
    print(result[:, :, 1])
    print(result.shape)














